-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 12:20:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`articles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `weight` FLOAT NULL,
  `height` FLOAT NULL,
  `lenght` FLOAT NULL,
  `width` FLOAT NULL,
  `price` DECIMAL(8,2) NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Phone number_UNIQUE` (`barcode` ASC) VISIBLE,
  INDEX `fk_Articles_Categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_Categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carriers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carriers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NOT NULL,
  `loadCapacity` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warehouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`warehouses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `streetNb` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `openingHours` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `employeeNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Personnel number_UNIQUE` (`employeeNumber` ASC) VISIBLE,
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `streetNumber` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deliveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deliveries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deliveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `originStreet` VARCHAR(45) NOT NULL,
  `originStreetNb` VARCHAR(45) NOT NULL,
  `originCity` VARCHAR(45) NOT NULL,
  `originPostalCode` VARCHAR(45) NOT NULL,
  `destinationStreet` VARCHAR(45) NOT NULL,
  `destinationStreetNb` VARCHAR(45) NOT NULL,
  `destinationCity` VARCHAR(45) NOT NULL,
  `destinationPostalCode` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `carrier_id` INT NULL,
  `client_id` INT NULL,
  `warehouse_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Firstname_UNIQUE` (`barcode` ASC) VISIBLE,
  INDEX `fk_Delivery_Carriers1_idx` (`carrier_id` ASC) VISIBLE,
  INDEX `fk_Deliveries_Customers1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_Deliveries_Warehouses1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_Carriers1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mydb`.`carriers` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Deliveries_Customers1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deliveries_Warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deliveries_have_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deliveries_have_articles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deliveries_have_articles` (
  `delivery_id` INT NULL,
  `article_id` INT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_Deliveries_has_Articles_Articles1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_Deliveries_has_Articles_Deliveries1_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_Deliveries_has_Articles_Deliveries1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `mydb`.`deliveries` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Deliveries_has_Articles_Articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`articles` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warehouses_have_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`warehouses_have_articles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`warehouses_have_articles` (
  `article_id` INT NULL,
  `warehouse_id` INT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_Articles_has_Warehouses_Warehouses1_idx` (`warehouse_id` ASC) VISIBLE,
  INDEX `fk_Articles_has_Warehouses_Articles1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_has_Warehouses_Articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`articles` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Articles_has_Warehouses_Warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warehouses_have_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`warehouses_have_employees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`warehouses_have_employees` (
  `warehouse_id` INT NULL,
  `employee_id` INT NULL,
  INDEX `fk_Warehouses_has_Staffs_Staffs1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_Warehouses_has_Staffs_Warehouses1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_Warehouses_has_Staffs_Warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Warehouses_has_Staffs_Staffs1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`days` ;

CREATE TABLE IF NOT EXISTS `mydb`.`days` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `day_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warehouses_have_days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`warehouses_have_days` ;

CREATE TABLE IF NOT EXISTS `mydb`.`warehouses_have_days` (
  `warehouse_id` INT NULL,
  `day_id` INT NULL,
  INDEX `fk_Warehouses_has_Days_Days1_idx` (`day_id` ASC) VISIBLE,
  INDEX `fk_Warehouses_has_Days_Warehouses1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_Warehouses_has_Days_Warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mydb`.`warehouses` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Warehouses_has_Days_Days1`
    FOREIGN KEY (`day_id`)
    REFERENCES `mydb`.`days` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
