-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 10:23:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cargoflow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cargoflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cargoflow` DEFAULT CHARACTER SET utf8 ;
USE `cargoflow` ;

-- -----------------------------------------------------
-- Table `cargoflow`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`categories` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`articles` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` BIGINT(30) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `weight` FLOAT NULL,
  `height` FLOAT NULL,
  `lenght` FLOAT NULL,
  `width` FLOAT NULL,
  `price` DECIMAL(8,2) NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Phone number_UNIQUE` (`barcode` ASC) VISIBLE,
  INDEX `fk_articles_categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_articles_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `cargoflow`.`categories` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`carriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`carriers` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`carriers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NOT NULL,
  `loadCapacity` INT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`warehouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`warehouses` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `streetNb` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`employees` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `employeeNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Personnel number_UNIQUE` (`employeeNumber` ASC) VISIBLE,
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`clients` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `streetNumber` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`deliveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`deliveries` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`deliveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` BIGINT(30) NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `carrier_id` INT NULL,
  `client_id` INT NULL,
  `warehouse_origin_id` INT NULL,
  `warehouse_destination_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Firstname_UNIQUE` (`barcode` ASC) VISIBLE,
  INDEX `fk_deliveries_carriers_idx` (`carrier_id` ASC) VISIBLE,
  INDEX `fk_deliveries_clients_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_deliveries_warehouses_origin_idx` (`warehouse_origin_id` ASC) VISIBLE,
  INDEX `fk_deliveries_warehouses_destination_idx` (`warehouse_destination_id` ASC) VISIBLE,
  CONSTRAINT `fk_deliveries_carriers`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `cargoflow`.`carriers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_deliveries_clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `cargoflow`.`clients` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_deliveries_warehouses_origin`
    FOREIGN KEY (`warehouse_origin_id`)
    REFERENCES `cargoflow`.`warehouses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_deliveries_warehouses_destination`
    FOREIGN KEY (`warehouse_destination_id`)
    REFERENCES `cargoflow`.`warehouses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`deliveries_have_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`deliveries_have_articles` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`deliveries_have_articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `delivery_id` INT NULL,
  `article_id` INT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_deliveries_have_articles_articles_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_deliveries_have_articles_deliveries_idx` (`delivery_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_deliveries_have_articles_deliveries`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `cargoflow`.`deliveries` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_deliveries_have_articles_articles`
    FOREIGN KEY (`article_id`)
    REFERENCES `cargoflow`.`articles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`warehouses_have_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`warehouses_have_articles` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`warehouses_have_articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_id` INT NULL,
  `warehouse_id` INT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_articles_have_warehouses_warehouses_idx` (`warehouse_id` ASC) VISIBLE,
  INDEX `fk_articles_have_warehouses_articles_idx` (`article_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articles_have_warehouses_articles`
    FOREIGN KEY (`article_id`)
    REFERENCES `cargoflow`.`articles` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_articles_have_warehouses_warehouses`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `cargoflow`.`warehouses` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`warehouses_have_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`warehouses_have_employees` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`warehouses_have_employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_id` INT NULL,
  `employee_id` INT NULL,
  INDEX `fk_warehouses_have_employees_employees_idx` (`employee_id` ASC) INVISIBLE,
  INDEX `fk_warehouses_have_employees_warehouses_idx` (`warehouse_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_warehouses_have_employees_warehouses`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `cargoflow`.`warehouses` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_warehouses_have_employees_employees`
    FOREIGN KEY (`employee_id`)
    REFERENCES `cargoflow`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`days` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`days` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `day_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargoflow`.`warehouses_have_days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargoflow`.`warehouses_have_days` ;

CREATE TABLE IF NOT EXISTS `cargoflow`.`warehouses_have_days` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_id` INT NULL,
  `day_id` INT NULL,
  `openingHours` TIME NULL,
  `closingHours` TIME NULL,
  INDEX `fk_warehouses_have_days_days_idx` (`day_id` ASC) VISIBLE,
  INDEX `fk_warehouses_have_days_warehouses_idx` (`warehouse_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_warehouses_have_days_warehouses`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `cargoflow`.`warehouses` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_warehouses_have_days_days`
    FOREIGN KEY (`day_id`)
    REFERENCES `cargoflow`.`days` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
